#%RAML 1.0 DataType
type: array
items:
  properties:
    departureDateTime:
      type: string
      required: true
      example: "2019-84-30T18:41:41.0987"
    fromLocation:
      type: string
      required: true
      example: "BEN-SG"
    toLocation:
      type: string
      required: true
      example: "KLG-MY"
    availableSeats:
      type: number
      required: true
      example: 50