#%RAML 1.0 Library
usage:
traits:
  transactionId : !include traits/header-transactionId-traits.raml
  departureLocationCode: !include traits/queryParams-departurelocationCode-trait.raml
  destinationLocationCode: !include traits/queryParam-destinationLocationCode-trait.raml 